### ISSUE TITLE
Advanced HTTP authentication mechanism in Jasper Report

### ISSUE THREAD

**Issue by tuspatil1** [TIBCOSoftware/jaspersoft-studio-ce#58] opened 2022-09-02 05:40 UTC
Hi Team,

We want to use URL as a datasource in JRXML inside JasperStudio, which requires HTTP authentication. Hence, we are using DataAdapter for invoking the URL & getting the data. As per our understanding, DataAdapter supports only basic HTTP authentication. But due to security concerns, we don't want to use dataadapter with basic HTTP authentication.

Please let us know if Jasper has any advanced authentication mechanisms while using a URL as a data source.

Thanks,
Tushar Patil

**Comment by maxrabbi** [comment] 2022-09-02 10:09
This bug entry seems a duplicate of the existing one you already opened: #57 
Please do not double the issues.

**Closed by maxrabbi** 2022-09-02 10:09 UTC

**Comment by tuspatil1** [comment] 2022-09-05 05:08
Hi Massimo,

We are getting "SSLHandshakeException" while evaluating dataSourceExpression which contains GET URL.

_**Caused by: net.sf.jasperreports.engine.JRRuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target**_

As per my understanding, we need to provide cerificate for GET URL. Do we have any option to provide certificate in Studio.

Thanks,
Tushar Patil

**Comment by maxrabbi** [comment] 2022-09-05 09:20
I think you should try using the Java keytool command to add the certificate to the proper keystore. 
Locate the one in your Jaspersoft Studio installation, because JSS standalone is started with its own JRE.
```
- example Mac: /Applications/TIBCO Jaspersoft Studio 6.20.0.app/Contents/Eclipse/features/jre.macosx.cocoa.x86_64.feature_11.0.8/adoptopenjdk_jre/Contents/Home/lib/security/cacerts
- example Win: C:\Program Files\TIBCO\Jaspersoft Studio-6.20.0\features\jre.win32.win32.x86_64.feature_11.0.8\adoptopenjdk_jre\lib\security\cacerts
- recall to change properly the \ into / for Windows system
```
An [old thread in the Community site](https://community.jaspersoft.com/questions/1183816/certificate-json-datasource-https-url), I think it's pretty close to what your use case.

That said please keep the discussion on one thread only. We left open the #57 and this was closed. Thanks.

Regards,
Massimo.
